version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_payment_db
    environment:
      - POSTGRES_PASSWORD=asdfg1234
    ports:
      -5432:5432
    volumes:
      -postgres-data:/var/lib/postgresql/data
  
  app:
    build: .
    depends_on:
      - postgres
    ports:
      -3001:3001
    environment:
      - DATABASE_URL: postgres://postgres:asdfg1234@postgres:5432/postgres
    command: >
      sh -c "cd packages/db &&
      npx prisma migrate dev --name init &&
      npx prisma generate &&
      npx prisma db seed &&
      cd ../../apps/user-app/bank-webhook &&
      npm run dev"

volumes:
  postgres-data:
  